BG_PATH = r'C:\Users\Ferhassio\PycharmProjects\SpacePiratesGame\content\bg_space.jpg'
CARD_DIR = r'C:\Users\Ferhassio\PycharmProjects\SpacePiratesGame\content'
VORTEX_PATH = r'C:\Users\Ferhassio\PycharmProjects\SpacePiratesGame\content\vortex.png'
PANEL_PATH = r'C:\Users\Ferhassio\PycharmProjects\SpacePiratesGame\content\panel.jpg'
PLACEHOLDER = r'C:\Users\Ferhassio\PycharmProjects\SpacePiratesGame\content\placeholder_rocket.png'
SHIP = r'C:\Users\Ferhassio\PycharmProjects\SpacePiratesGame\content\ship.png'